eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: 80
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.eurekaserver.uri:http://euerkaserver.local.pcfdev.io}/eurekaserver/eureka


spring:
  application:
    name: demobootadmin



management:
  security:
    enabled: false

server:
  port: 9001
security:
  basic:
    enabled: false